set_property PACKAGE_PIN P17 [get_ports clk100]
set_property PACKAGE_PIN R10 [get_ports key]

set_property PACKAGE_PIN U3 [get_ports vga_hsync]
set_property PACKAGE_PIN R6 [get_ports vga_vsync]

set_property PACKAGE_PIN P3 [get_ports {vga_blue[4]}]
set_property PACKAGE_PIN K6 [get_ports {vga_blue[3]}]
set_property PACKAGE_PIN P4 [get_ports {vga_blue[2]}]
set_property PACKAGE_PIN R2 [get_ports {vga_blue[1]}]
set_property PACKAGE_PIN P5 [get_ports {vga_blue[0]}]

set_property PACKAGE_PIN P2 [get_ports {vga_green[5]}]
set_property PACKAGE_PIN N5 [get_ports {vga_green[4]}]
set_property PACKAGE_PIN N6 [get_ports {vga_green[3]}]
set_property PACKAGE_PIN N1 [get_ports {vga_green[2]}]
set_property PACKAGE_PIN M6 [get_ports {vga_green[1]}]
set_property PACKAGE_PIN N2 [get_ports {vga_green[0]}]

set_property PACKAGE_PIN T1 [get_ports {vga_red[4]}]
set_property PACKAGE_PIN T3 [get_ports {vga_red[3]}]
set_property PACKAGE_PIN R1 [get_ports {vga_red[2]}]
set_property PACKAGE_PIN R3 [get_ports {vga_red[1]}]
set_property PACKAGE_PIN R5 [get_ports {vga_red[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_green[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_green[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_green[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_green[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_green[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_green[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk100]
set_property IOSTANDARD LVCMOS33 [get_ports key]
set_property IOSTANDARD LVCMOS33 [get_ports vga_hsync]
set_property IOSTANDARD LVCMOS33 [get_ports vga_vsync]

set_property IOSTANDARD LVCMOS33 [get_ports {d[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {d[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {d[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {d[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {d[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {d[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {d[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {d[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports pclk]
set_property IOSTANDARD LVCMOS33 [get_ports href]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]

set_property PACKAGE_PIN P18 [get_ports href]
set_property PACKAGE_PIN M16 [get_ports vsync]
set_property PACKAGE_PIN N17 [get_ports xclk]
set_property PACKAGE_PIN M14 [get_ports pclk]
set_property PACKAGE_PIN L15 [get_ports I2C_SDAT]
set_property PACKAGE_PIN M17 [get_ports I2C_SCLK]

set_property PACKAGE_PIN R18 [get_ports {d[0]}]
set_property PACKAGE_PIN R15 [get_ports {d[1]}]
set_property PACKAGE_PIN T18 [get_ports {d[2]}]
set_property PACKAGE_PIN N15 [get_ports {d[3]}]
set_property PACKAGE_PIN N14 [get_ports {d[4]}]
set_property PACKAGE_PIN N16 [get_ports {d[5]}]
set_property PACKAGE_PIN P14 [get_ports {d[6]}]
set_property PACKAGE_PIN L14 [get_ports {d[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports xclk]
set_property IOSTANDARD LVCMOS33 [get_ports I2C_SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports I2C_SDAT]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets pclk_IBUF]

set_property IOSTANDARD LVCMOS33 [get_ports pwdm]
set_property IOSTANDARD LVCMOS33 [get_ports reset_cam]
set_property PACKAGE_PIN T15 [get_ports pwdm]
set_property PACKAGE_PIN P15 [get_ports reset_cam]

set_property IOSTANDARD LVCMOS33 [get_ports sram_ce_r]
set_property IOSTANDARD LVCMOS33 [get_ports sram_lb_r]
set_property IOSTANDARD LVCMOS33 [get_ports sram_oe_r]
set_property IOSTANDARD LVCMOS33 [get_ports sram_ub_r]
set_property IOSTANDARD LVCMOS33 [get_ports sram_we_r]
set_property PACKAGE_PIN E3 [get_ports sram_ce_r]
set_property PACKAGE_PIN D5 [get_ports sram_lb_r]
set_property PACKAGE_PIN D4 [get_ports sram_oe_r]
set_property PACKAGE_PIN B2 [get_ports sram_ub_r]
set_property PACKAGE_PIN D3 [get_ports sram_we_r]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_data[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_data[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_data[0]}]
set_property PACKAGE_PIN G4 [get_ports {sram_data[0]}]
set_property PACKAGE_PIN G3 [get_ports {sram_data[1]}]
set_property PACKAGE_PIN J3 [get_ports {sram_data[2]}]
set_property PACKAGE_PIN J2 [get_ports {sram_data[3]}]
set_property PACKAGE_PIN K2 [get_ports {sram_data[4]}]
set_property PACKAGE_PIN K1 [get_ports {sram_data[5]}]
set_property PACKAGE_PIN H6 [get_ports {sram_data[6]}]
set_property PACKAGE_PIN H5 [get_ports {sram_data[7]}]
set_property PACKAGE_PIN M1 [get_ports {sram_data[8]}]
set_property PACKAGE_PIN K3 [get_ports {sram_data[9]}]
set_property PACKAGE_PIN L3 [get_ports {sram_data[10]}]
set_property PACKAGE_PIN M3 [get_ports {sram_data[11]}]
set_property PACKAGE_PIN M2 [get_ports {sram_data[12]}]
set_property PACKAGE_PIN K5 [get_ports {sram_data[13]}]
set_property PACKAGE_PIN L4 [get_ports {sram_data[14]}]
set_property PACKAGE_PIN L6 [get_ports {sram_data[15]}]

set_property PACKAGE_PIN B3 [get_ports {sram_addr[0]}]
set_property PACKAGE_PIN A1 [get_ports {sram_addr[1]}]
set_property PACKAGE_PIN B1 [get_ports {sram_addr[2]}]
set_property PACKAGE_PIN A3 [get_ports {sram_addr[3]}]
set_property PACKAGE_PIN A4 [get_ports {sram_addr[4]}]
set_property PACKAGE_PIN B4 [get_ports {sram_addr[5]}]
set_property PACKAGE_PIN C4 [get_ports {sram_addr[6]}]
set_property PACKAGE_PIN D7 [get_ports {sram_addr[7]}]
set_property PACKAGE_PIN E7 [get_ports {sram_addr[8]}]
set_property PACKAGE_PIN E5 [get_ports {sram_addr[9]}]
set_property PACKAGE_PIN E6 [get_ports {sram_addr[10]}]
set_property PACKAGE_PIN C7 [get_ports {sram_addr[11]}]
set_property PACKAGE_PIN D8 [get_ports {sram_addr[12]}]
set_property PACKAGE_PIN A5 [get_ports {sram_addr[13]}]
set_property PACKAGE_PIN A6 [get_ports {sram_addr[14]}]
set_property PACKAGE_PIN B6 [get_ports {sram_addr[15]}]
set_property PACKAGE_PIN B7 [get_ports {sram_addr[16]}]
set_property PACKAGE_PIN C5 [get_ports {sram_addr[17]}]
set_property PACKAGE_PIN C6 [get_ports {sram_addr[18]}]	

set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_txd]	
set_property PACKAGE_PIN U7 [get_ports uart_rxd]
set_property PACKAGE_PIN U8 [get_ports uart_txd]
	
	
	
	