# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/70919/Desktop/beta8vivado/beta8vivado.cache/wt [current_project]
set_property parent.project_path C:/Users/70919/Desktop/beta8vivado/beta8vivado.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/70919/Desktop/beta8vivado/beta8vivado.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/70919/Desktop/beta8vivado/beta8vivado.srcs/sources_1/new/I2C_Controller.v
  C:/Users/70919/Desktop/beta8vivado/beta8vivado.srcs/sources_1/new/I2C_OV7670_RGB565_Config.v
  C:/Users/70919/Desktop/beta8vivado/beta8vivado.srcs/sources_1/new/IICctrl.v
  C:/Users/70919/Desktop/beta8vivado/beta8vivado.srcs/sources_1/new/IICctrl_0.v
  C:/Users/70919/Desktop/beta8vivado/beta8vivado.srcs/sources_1/new/camCap.v
  C:/Users/70919/Desktop/beta8vivado/beta8vivado.srcs/sources_1/new/camCap_0.v
  C:/Users/70919/Desktop/beta8vivado/beta8vivado.srcs/sources_1/new/difference.v
  C:/Users/70919/Desktop/beta8vivado/beta8vivado.srcs/sources_1/new/dilation.v
  C:/Users/70919/Desktop/beta8vivado/beta8vivado.srcs/sources_1/new/erosion.v
  C:/Users/70919/Desktop/beta8vivado/beta8vivado.srcs/sources_1/new/erosion2.v
  C:/Users/70919/Desktop/beta8vivado/beta8vivado.srcs/sources_1/new/goal_position.v
  C:/Users/70919/Desktop/beta8vivado/beta8vivado.srcs/sources_1/new/key.v
  C:/Users/70919/Desktop/beta8vivado/beta8vivado.srcs/sources_1/new/line_shift_3X3_1bit.v
  C:/Users/70919/Desktop/beta8vivado/beta8vivado.srcs/sources_1/new/line_shift_3X3_1bit_di.v
  C:/Users/70919/Desktop/beta8vivado/beta8vivado.srcs/sources_1/new/line_shift__9X9_1Bit.v
  C:/Users/70919/Desktop/beta8vivado/beta8vivado.srcs/sources_1/new/uart_recv.v
  C:/Users/70919/Desktop/beta8vivado/beta8vivado.srcs/sources_1/new/uart_send.v
  C:/Users/70919/Desktop/beta8vivado/beta8vivado.srcs/sources_1/new/vga_output.v
  C:/Users/70919/Desktop/beta8vivado/beta8vivado.srcs/sources_1/new/topvivado.v
}
read_ip -quiet C:/Users/70919/Desktop/beta8vivado/beta8vivado.srcs/sources_1/ip/c_shift_ram_3/c_shift_ram_3.xci
set_property used_in_implementation false [get_files -all c:/Users/70919/Desktop/beta8vivado/beta8vivado.srcs/sources_1/ip/c_shift_ram_3/c_shift_ram_3_ooc.xdc]

read_ip -quiet C:/Users/70919/Desktop/beta8vivado/beta8vivado.srcs/sources_1/ip/c_shift_ram_2/c_shift_ram_2.xci
set_property used_in_implementation false [get_files -all c:/Users/70919/Desktop/beta8vivado/beta8vivado.srcs/sources_1/ip/c_shift_ram_2/c_shift_ram_2_ooc.xdc]

read_ip -quiet C:/Users/70919/Desktop/beta8vivado/beta8vivado.srcs/sources_1/ip/c_shift_ram_1/c_shift_ram_1.xci
set_property used_in_implementation false [get_files -all c:/Users/70919/Desktop/beta8vivado/beta8vivado.srcs/sources_1/ip/c_shift_ram_1/c_shift_ram_1_ooc.xdc]

read_ip -quiet C:/Users/70919/Desktop/beta8vivado/beta8vivado.srcs/sources_1/ip/c_shift_ram_0/c_shift_ram_0.xci
set_property used_in_implementation false [get_files -all c:/Users/70919/Desktop/beta8vivado/beta8vivado.srcs/sources_1/ip/c_shift_ram_0/c_shift_ram_0_ooc.xdc]

read_ip -quiet C:/Users/70919/Desktop/beta8vivado/beta8vivado.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/70919/Desktop/beta8vivado/beta8vivado.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/70919/Desktop/beta8vivado/beta8vivado.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/70919/Desktop/beta8vivado/beta8vivado.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet C:/Users/70919/Desktop/beta8vivado/beta8vivado.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all c:/Users/70919/Desktop/beta8vivado/beta8vivado.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/70919/Desktop/beta8vivado/beta8vivado.srcs/constrs_1/new/xdc.xdc
set_property used_in_implementation false [get_files C:/Users/70919/Desktop/beta8vivado/beta8vivado.srcs/constrs_1/new/xdc.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top vivadotop -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef vivadotop.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file vivadotop_utilization_synth.rpt -pb vivadotop_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
